#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/create_network
- name: Create Docker network
  docker_network:
    name: app_network
    driver: bridge
  vars:
    ansible_python_interpreter: /usr/bin/python3
