#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_app
- name: Run simple API container
  docker_container:
    name: simple-api
    image: lilgrand/tp-devops-simple-api
    state: started
    restart_policy: always
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    networks:
      - name: app_network
