#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_database
- name: Run database container
  docker_container:
    name: database
    image: lilgrand/tp-devops-database
    state: started
    restart_policy: always
    env:
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: app_network

