name: Deploy to Server

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Publish]
    types:
      - completed

jobs:
  deploy:
    name: Ansible Deployment
    runs-on: ubuntu-24.04
    if: ${{github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
